insert into categories (name) values ('category 01');
insert into categories (name) values ('category 02');
insert into categories (name) values ('category 03');
insert into categories (name) values ('category 04');
insert into categories (name) values ('category 05');
insert into categories (name) values ('category 06');
insert into categories (name) values ('category 07');
insert into categories (name) values ('category 08');

insert into web_pages (title, url, category_id) values ('Title 01', 'Url 01', 1);
insert into web_pages (title, url, category_id) values ('Title 02', 'Url 02', 1);
insert into web_pages (title, url, category_id) values ('Title 03', 'Url 03', 2);
insert into web_pages (title, url, category_id) values ('Title 04', 'Url 04', 5);
insert into web_pages (title, url, category_id) values ('Title 05', 'Url 05', 1);
insert into web_pages (title, url, category_id) values ('Title 06', 'Url 06', 2);
insert into web_pages (title, url, category_id) values ('Title 07', 'Url 07', 1);
insert into web_pages (title, url, category_id) values ('Title 08', 'Url 08', 7);
insert into web_pages (title, url, category_id) values ('Title 09', 'Url 09', 2);
insert into web_pages (title, url, category_id) values ('Title 10', 'Url 10', 1);
insert into web_pages (title, url, category_id) values ('Title 11', 'Url 11', 1);
insert into web_pages (title, url, category_id) values ('Title 12', 'Url 12', 5);
insert into web_pages (title, url, category_id) values ('Title 13', 'Url 13', 5);